version: "3"

services:
  frontend:
    container_name: "wordle"
    build: 
      context: .  # Location of dockerfile
      dockerfile: Dockerfile  # Name of dockerfile
    environment:
      CHOKIDAR_USEPOLLING: true # Required for React hot-reload when files change
      NODE_ENV: development
    ports:
      - '8080:3000' # Expose ports
    stdin_open: true
    volumes:
      - .:/app  # Map host working src directory to container src directory
      - /app/node_modules # Excluding node_modules