version: "3"

services:
  frontend:
    container_name: "wordle-dev"
    build: 
      context: .
      dockerfile: Dockerfile.dev
    environment:
      CHOKIDAR_USEPOLLING: true
      NODE_ENV: development
    ports:
      - '8080:3000'
    stdin_open: true
    volumes:
      - .:/app
      - /app/node_modules