version: "3"

services:
  prod-frontend:
    container_name: "wordle-prod"
    build:
      context: ./frontend # Where the dockerfile will be executed (root of our project)
      dockerfile: ./docker/Dockerfile.prod # Dir of dockerfile
    ports:
      - "3000:80" # Expose ports
