# On Push:
#   This action will run tests on the Node project:
#     If tests pass: 
#       Deploy new website
#       Push new Docker image to DockerHub
name: Push new image to AWS ECR

on:
  push:
    branches: [main]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          cache: "npm"

      - name: Run tests
        run: |
          npm ci
          npm run test
          npm run build
        env:
          CI: false

      - name: Deploy to production
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: build
