# On pull request, this action will run tests
name: Run Tests

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./root/frontend
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          cache: "npm"
          cache-dependency-path: "./root/frontend/package-lock.json"

      - name: Run frontend tests
        run: |
          npm ci
          npm run test
